### ISSUE TITLE
Debug log is empty?

### ISSUE THREAD

**Issue by iaz3** [iaz3/wrye-bash#2]
For some reason the debug log is always empty. It's something after the program start.

**Comment by iaz3** [comment]
Present in the main dev repository.

**Comment by Utumno** [comment]
bashBugDump.log ?

**Comment by iaz3** [comment]
Yes

**Comment by Utumno** [comment]
Do you generate it as in here: https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Reporting-a-bug#the-bashbugdumplog ?

**Comment by iaz3** [comment]
For my testing purposes i have debug on, via the -d flag.

Always seems to be empty, but i could have sworn it wasent before. I also checked based on random earlier commits from dev, and also the master branch and didnt seem to get anything. And as of just now, on the latest release. 

The first time i ran it, i got something, up until i picked a game via the selection screen. Then it was cleared.

**Comment by Utumno** [comment]
Run the bat

**Comment by iaz3** [comment]
Running the bat in release python source:

In log, before picking a game, slight change in indentation. The exe and source must do something different there?

No change in end result. Debug log still empty.
Occurs regardless of which game is picked.(tested on a whim)

**Comment by Utumno** [comment]
works for me - investigate your setup

`C:\path\to\Mopy>c:\path\to\Python27\python.exe "Wrye Bash Launcher.pyw" -d` ?

**Comment by iaz3** [comment]
Yes
And the bat file

It's weird, since i know it's worked before

And i'm testing it with both the code i'm working on, and source downloads

Does it have setting files/ini in random places that could somehow force it to ignore the debug, or clear it whenever you pick a game? Does it not like having both skyrim and oblivion as options and not being told specifically which game to use through command line options?

**Comment by Utumno** [comment]
Nope and nope - weird...

Something in your setup - try a fresh install

**Comment by iaz3** [comment]
Fresh install of what exactly? For teh testing just now i was using freshly downloaded WB from teh releases tab

I use MO, so skyrim is clean. I havent actually started modding/playing oblivion so thats clean too.

And i wasent testing through MO, so it isnt something it's doing.

**Comment by iaz3** [comment]
Further testing as of just now: It doesnt empty out when i specified the --game command line option with oblivion OR skyrim.

With this in mind, it must be something to do with the GUI game picker. The log is only cleared AFTER selecting a game through there, but not if you quit.

**Comment by Utumno** [comment]
Ok was a fresh install - no clue here

**Comment by iaz3** [comment]
I assume the problem only presents itself when you have multiple games it can detect. Previously i had never owned oblivion, so only had skyrim, and never had the problem.

**Comment by Utumno** [comment]
So you were quitting ? yea no log is created if you don't pick a game ofc

**Comment by iaz3** [comment]
No no, quitting from the GUI selection is the only result that generates text in the log

After picking a game the log is cleared out

A log is created whetehr you pick a game or not (and i just now double tested this)

**Comment by Utumno** [comment]
No clue at iaz - I have no more time for this now sorry

**Comment by iaz3** [comment]
Yeah, not the most important thing right now

**Comment by Utumno** [comment]
From: https://github.com/iaz3/wrye-bash/commit/2d6bbd1874182623c015d0a9ec28f944d1201b52#commitcomment-16866607

I've been using a workaround, but the issue remains.

A recap of when it occurs:
It seems to only occur in situations where you

   -  have multiple games installed
   - Game not specified on commandline
   -  Do NOT click exit on the gui game selector, in which case you get the enviroment info from bash.dump_environment

The workaround is to specify the game on the command line

Will have a look - I guess specifying the game from the ini (as I do) is working this around also

Just to be sure - you had not asked about the importers logs (in the refactoring you have been doing) ? Those are ok - right ?

**Comment by iaz3** [comment]
Yeah, it just doesnt seem to like the GUI game selector. Maybe wx is resetting stderr and stdout? 

At some point we should probably just use the logger module, and not rely on print.

Importers logs?

**Comment by Utumno** [comment]
> At some point we should probably just use the logger module, and not rely on print.

In my mind definitely but much later - full refactoring on now, much deeper issues till the code is ready - check my wip

> Importers logs?

I thought you had mentioned those not working

Will test the dialog - so "bashbugdump.log empty when selecting game fom the dialog" is the bug, right ?

**Comment by iaz3** [comment]
Definitely much later, yeah.

> Will test the dialog - so "bashbugdump.log empty when selecting game fom the dialog" is the bug, right ?

Yeah, thats the bug.

**Comment by Utumno** [comment]
When staring Bash via the bat file it's ok - it happens only when starting it using `C:\path\to\Mopy>"Wrye Bash Launcher.pyw" -d` directly. Known iissue - see https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug#the-bashbugdumplog

Not sure why - a pythonw thing ?

Standalone should be immune - right ?

**Comment by iaz3** [comment]
No, it's an issue in any case where the gui game selection is used.

I double checked just now, and that DOES includes the latest standalone and when using "Wrye Bash Debug.bat".

And i dont see where that says that using the flag directly is a known issue? All it says is calling "C:\path\to\Mopy>"Wrye Bash Launcher.pyw" -d" wont work, but thats just because python isnt a magic executable on windows. You cant run ANY python script by just calling it. (Not easily, at least. IIRC you need a bunch of registry hacks, but idk. I never got it to work)
it needs to be "python [Some python script] [any arguments it might have]"

I imagine it hasent been noticed because people either

- Dont need the debug log
- Dont have multiple games installed, so dont ever use the gui selector
- Have their shortcuts specify the game with the -g switch
- Some variation of the above

**Comment by Utumno** [comment]
Hmm I have 3 installed just to get the launcher - cause for me running the bat works. It's the launcher that does its tricks ? http://stackoverflow.com/a/17245543/281545

> calling "C:\path\to\Mopy>"Wrye Bash Launcher.pyw" -d" wont work

I mean it does not produce a log as you report - for me it launches fine (see link above)

Hmmm needs needs investigation then

**Comment by iaz3** [comment]
Do you have multiple supported games installed in a way that wrye bash can find them?(IE, both oblivion and skyrim installed)

**Comment by Utumno** [comment]
Yes yes
![kkk](https://cloud.githubusercontent.com/assets/1365079/14133625/71c2b598-f659-11e5-89a4-71ed98e1369f.jpg)


And here is what is produced if I click on oblivion:
```

Wrye Bash starting
Using Wrye Bash Version 307
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs 
Searching for game to manage:
bush.py   71 _supportedGames: Detected the following supported games via Windows Registry:
bush.py   73 _supportedGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   73 _supportedGames:  skyrim: C:\GAMES\Skyrim
bush.py  131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  141 _detectGames: No known game in parent directory of Mopy: C:\Dropbox\eclipse_workspaces\python\wrye-bash
bush.py  172 setGame: No preferred game specified.
bush.py  131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  141 _detectGames: No known game in parent directory of Mopy: C:\Dropbox\eclipse_workspaces\python\wrye-bash
bush.py  152 __setGame: Specified game "oblivion" was found: C:\GAMES\TESIV\Oblivion
testing UAC
mods_metadata.py  219 __init__: Using libbsa API version: 2.0.0
mods_metadata.py  225 __init__: Using LOOT API version: 0.6.0
load_order.py  329 <module>: Using libloadorder API version: 7.6.1

```

**Comment by iaz3** [comment]
I dont know why it would just be a problem for me
i've never messed with or changed any settings, and i did it on clean installs and stuff.

Nothing should be different from anything else.

**Comment by Utumno** [comment]
Well yes - it may be a problem for whoever has not installed python launcher for windows maybe ? That's an issue. Me on the other hand I had no problem whatsoever - apart the "C:\path\to\Mopy>"Wrye Bash Launcher.pyw" -d" - with the python version. Will test the standalone later

**Comment by iaz3** [comment]
For me it doesnt matter what it is.

And a .pyw, as far as i know, is exactly like any normal python file. Except it opens on windows without a commandline. Thats the only difference.
